import React, { useState } from 'react';
import { Download, Mail, Volume2, Copy, Check, Star, BookOpen, Sparkles } from 'lucide-react';
import confetti from 'canvas-confetti';
import { jsPDF } from 'jspdf';
import MathRenderer from './MathRenderer';

export default function SolutionViewer({ solutionData, onOpenEmailModal, lang }) {
  const [copied, setCopied] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  if (!solutionData) return null;

  const currentLang = lang || solutionData.language || 'en';
  const explanationText = solutionData.explanation?.[currentLang] ||
    solutionData.explanation?.['en'] ||
    solutionData.solutions?.[currentLang]?.medium ||
    solutionData.solutions?.['en']?.medium ||
    '';

  const triggerConfetti = () => {
    confetti({
      particleCount: 25,
      spread: 45,
      origin: { y: 0.7 }
    });
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(explanationText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeak = () => {
    if (!('speechSynthesis' in window)) {
      alert('Speech synthesis not supported in this browser.');
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      const plainText = explanationText
        .replace(/[#$*]/g, '')
        .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '$1 over $2')
        .replace(/\\times/g, 'times');

      const utterance = new SpeechSynthesisUtterance(plainText);
      utterance.lang = currentLang === 'te' ? 'te-IN' : 'en-IN';
      utterance.rate = 0.95;
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  const handleDownloadPdf = () => {
    triggerConfetti();
    const doc = new jsPDF();
    const margin = 15;
    let y = 20;

    doc.setFillColor(192, 30, 46);
    doc.rect(0, 0, 210, 25, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text("SSC Math Mitra (గణిత మిత్ర) - 10th Class Solution", margin, 16);

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(12);
    y = 35;
    doc.text(`Chapter: ${solutionData.chapter_en} (${solutionData.chapter_te})`, margin, y);
    y += 7;
    doc.text(`Reference: ${solutionData.exercise_reference || 'Textbook Practice'} | ${solutionData.page_reference}`, margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const cleanText = explanationText.replace(/[#$*]/g, '');
    const splitExplanation = doc.splitTextToSize(cleanText, 180);
    doc.text(splitExplanation, margin, y);

    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text("Generated by SSC Math Mitra • Clear guidance for 10th Class Students", margin, 285);

    doc.save(`Math_Mitra_${solutionData.chapter_en}_Solution.pdf`);
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-6 bg-white rounded-3xl p-6 sm:p-8 shadow-md border border-slate-200 animate-slide-up space-y-4">
      {/* Top Bar with Badges & Action Buttons */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3.5">
        <div className="flex flex-wrap items-center gap-2">
          <span className="px-3 py-1 rounded-full text-xs font-bold bg-amber-50 text-amber-900 border border-amber-200">
            {currentLang === 'te' ? solutionData.chapter_te : solutionData.chapter_en}
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-100 text-slate-700">
            {solutionData.exercise_reference}
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-medium text-slate-500">
            {solutionData.page_reference}
          </span>
        </div>

        {/* Action Tools */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleSpeak}
            className={`p-2.5 rounded-xl border transition-all cursor-pointer ${
              isSpeaking
                ? 'bg-amber-100 text-amber-900 border-amber-300 animate-pulse'
                : 'bg-white text-slate-600 hover:text-amber-800 border-slate-200 hover:bg-slate-50'
            }`}
            title="Read Aloud (చదివి వినిపించు)"
          >
            <Volume2 className="w-4 h-4" />
          </button>

          <button
            onClick={handleCopy}
            className="p-2.5 rounded-xl border border-slate-200 bg-white text-slate-600 hover:text-slate-900 transition-all cursor-pointer"
            title="Copy Text"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
          </button>

          <button
            onClick={handleDownloadPdf}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold transition-all cursor-pointer"
            title="Download PDF"
          >
            <Download className="w-3.5 h-3.5 text-rose-600" />
            <span className="hidden sm:inline">PDF</span>
          </button>

          <button
            onClick={() => onOpenEmailModal(solutionData)}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#c01e2e] hover:bg-[#a51927] text-white text-xs font-bold shadow-xs transition-all cursor-pointer"
            title="Send to Gmail"
          >
            <Mail className="w-3.5 h-3.5" />
            <span>{currentLang === 'te' ? 'ఈమెయిల్' : 'Email'}</span>
          </button>
        </div>
      </div>

      {/* Clean ChatGPT-style solution layout */}
      <div className="bg-[#fafaf8] rounded-2xl p-5 sm:p-7 border border-[#edece8]">
        <MathRenderer content={explanationText} />
      </div>

      {/* Key Formulas */}
      {solutionData.formulas && solutionData.formulas.length > 0 && (
        <div className="p-4 rounded-2xl bg-amber-50/50 border border-amber-200/80 mt-4">
          <h4 className="text-xs font-bold text-amber-900 uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <Star className="w-3.5 h-3.5 fill-current text-amber-500" />
            {currentLang === 'te' ? 'గుర్తుంచుకోవలసిన ముఖ్య సూత్రాలు:' : 'Key Applicable Formulas:'}
          </h4>
          <div className="flex flex-wrap gap-2">
            {solutionData.formulas.map((formula, idx) => (
              <div key={idx} className="bg-white px-3.5 py-1.5 rounded-xl border border-amber-200 text-xs font-mono shadow-2xs">
                <MathRenderer content={`$${formula}$`} />
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
